els-ASAP auto commit file/tag dapl-2.1.5-1.el7.src.rpm

diff --git a/src/dapl.spec.in b/src/dapl.spec.in
--- a/src/dapl.spec.in
+++ b/src/dapl.spec.in
@@ -1,5 +1,5 @@
 # Copyright (c) 2002-2005, Network Appliance, Inc. All rights reserved.
-# Copyright (c) 2007, Intel Corporation. All rights reserved.
+# Copyright (c) 2007-2015, Intel Corporation. All rights reserved.
 #
 # This Software is licensed under one of the following licenses:
 #
@@ -31,20 +31,26 @@
 # uDAT and uDAPL 2.0 Registry RPM SPEC file
 #
 # $Id: $
+# don't fail when not given extra FLAGS:
+%{!?_CPPFLAGS: %define _CPPFLAGS ""}
+%{!?_LDFLAGS: %define _LDFLAGS ""}
+%{!?_CONF: %define _CONF ""}
+
 Name: dapl
 Version: @VERSION@
 Release: 1%{?dist}
-Summary: A Library for userspace access to RDMA devices using OS Agnostic DAT APIs.
+Summary: A Library for userspace access to RDMA devices using OS Agnostic DAT APIs, proxy daemon for offloading RDMA 
 
 Group: System Environment/Libraries
 License: Dual GPL/BSD/CPL
 Url: http://openfabrics.org/
 Source: http://www.openfabrics.org/downloads/%{name}/%{name}-%{version}.tar.gz
-BuildRoot: %(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)
+BuildRoot: %{_topdir}/BUILDROOT
+Obsoletes: intel-mic-ofed-dapl
 Requires(post): /sbin/ldconfig
 Requires(postun): /sbin/ldconfig
-Requires(post): sed
-Requires(post): coreutils
+Requires(post): /sbin/chkconfig
+Requires(preun): /sbin/chkconfig
 
 %description
 Along with the OpenFabrics kernel drivers, libdat and libdapl provides a userspace
@@ -54,6 +60,8 @@ atomic operations and rdma write with immediate data.
 %package devel
 Summary: Development files for the libdat and libdapl libraries
 Group: System Environment/Libraries
+Requires: %{name} = %{version}-%{release}
+Obsoletes: intel-mic-ofed-dapl-devel
 
 %description devel
 Header files for libdat and libdapl library.
@@ -61,6 +69,7 @@ Header files for libdat and libdapl library.
 %package devel-static
 Summary: Static development files for libdat and libdapl library
 Group: System Environment/Libraries
+Obsoletes: intel-mic-ofed-dapl-devel-static
  
 %description devel-static
 Static libraries for libdat and libdapl library.
@@ -69,6 +78,7 @@ Static libraries for libdat and libdapl library.
 Summary: Test suites for uDAPL library
 Group: System Environment/Libraries
 Requires: %{name} = %{version}-%{release}
+Obsoletes: intel-mic-ofed-dapl-utils
 
 %description utils
 Useful test suites to validate uDAPL library API's.
@@ -77,26 +87,50 @@ Useful test suites to validate uDAPL library API's.
 %setup -q
 
 %build
-%configure --enable-ext-type=ib 
+%configure CPPFLAGS=%{_CPPFLAGS} LDFLAGS=%{_LDFLAGS} %{_CONF}
+
 make %{?_smp_mflags}
 
 %install
-rm -rf %{buildroot}
-make DESTDIR=%{buildroot} install
+rm -rf $RPM_BUILD_ROOT
+make install DESTDIR=$RPM_BUILD_ROOT
+
 # remove unpackaged files from the buildroot
 rm -f %{buildroot}%{_libdir}/*.la
+
+# make init.d so we can exclude it later:
+mkdir -p %{buildroot}%{_sysconfdir}/init.d
+touch mcm-files
 
 %clean
 rm -rf %{buildroot}
 
-%post -p /sbin/ldconfig
-%postun -p /sbin/ldconfig
+%post
+# fix problem with older dapl packages that clobber dat.conf when updating
+cp %{_sysconfdir}/dat.conf /tmp/%{version}-dat.conf
+/sbin/ldconfig
 
-%files
+if [ $1 -gt 1 ]; then
+	/sbin/chkconfig --add mpxyd &> /dev/null || true
+	service mpxyd start
+elif [ $1 -gt 2 ]; then
+	service mpxyd restart
+fi
+
+%preun
+if [ -f /etc/init.d/mpxyd ]; then
+	/sbin/chkconfig --del mpxyd &> /dev/null
+	service mpxyd stop
+fi
+
+%postun 
+/sbin/ldconfig
+
+%files -f mcm-files
 %defattr(-,root,root,-)
 %{_libdir}/libda*.so.*
-%{_sysconfdir}/dat.conf
-%doc AUTHORS README COPYING ChangeLog LICENSE.txt LICENSE2.txt LICENSE3.txt
+%config %{_sysconfdir}/dat.conf
+%doc AUTHORS README COPYING ChangeLog LICENSE.txt LICENSE2.txt LICENSE3.txt README.mcm
 
 %files devel
 %defattr(-,root,root,-)
@@ -114,7 +148,38 @@ rm -rf %{buildroot}
 %{_mandir}/man1/*.1*
 %{_mandir}/man5/*.5*
 
+%triggerpostun -- dapl < 2.0.35-1
+# fix problem with older dapl packages that clobber dat.conf during update
+mv /tmp/%{version}-dat.conf %{_sysconfdir}/dat.conf
+
 %changelog
+* Mon May 26 2015 Arlin Davis <ardavis@ichips.intel.com> - 2.1.5
+- DAT/DAPL Version 2.1.5 Release 1, OFED 3.18
+
+* Thu Mar 19 2015 Arlin Davis <ardavis@ichips.intel.com> - 2.1.4
+- DAT/DAPL Version 2.1.4 Release 1, OFED 3.18
+
+* Mon Dec 15 2014 Arlin Davis <ardavis@ichips.intel.com> - 2.1.3
+- DAT/DAPL Version 2.1.3 Release 1, OFED 3.18 RC
+
+* Tue Sep 2 2014 Arlin Davis <ardavis@ichips.intel.com> - 2.1.2
+- DAT/DAPL Version 2.1.2 Release 1, OFED 3.12-1
+
+* Wed Aug 13 2014 Arlin Davis <ardavis@ichips.intel.com> - 2.1.1
+- DAT/DAPL Version 2.1.1 Release 1, OFED 3.12-1
+
+* Fri Jul 18 2014 Arlin Davis <ardavis@ichips.intel.com> - 2.1.0
+- DAT/DAPL Version 2.1.0 Release 1, add MIC support, OFED 3.12-1
+
+* Sun May 4 2014 Arlin Davis <ardavis@ichips.intel.com> - 2.0.42
+- DAT/DAPL Version 2.0.42 Release 1, OFED 3.12 GA
+
+* Fri Mar 14 2014 Arlin Davis <ardavis@ichips.intel.com> - 2.0.41
+- DAT/DAPL Version 2.0.41 Release 1, OFED 3.12 GA
+
+* Mon Feb 10 2014 Arlin Davis <ardavis@ichips.intel.com> - 2.0.40
+- DAT/DAPL Version 2.0.40 Release 1, OFED 3.12
+
 * Thu Oct 3 2013 Arlin Davis <ardavis@ichips.intel.com> - 2.0.39
 - DAT/DAPL Version 2.0.39 Release 1, OFED 3.5-2 
 
@@ -124,7 +189,7 @@ rm -rf %{buildroot}
 * Thu Jun 6 2013 Arlin Davis <ardavis@ichips.intel.com> - 2.0.37
 - DAT/DAPL Version 2.0.37 Release 1, OFED 3.5.2 
 
-* Thu Aug 5 2012 Arlin Davis <ardavis@ichips.intel.com> - 2.0.36
+* Sun Aug 5 2012 Arlin Davis <ardavis@ichips.intel.com> - 2.0.36
 - DAT/DAPL Version 2.0.36 Release 1, OFED 3.x 
 
 * Mon Apr 23 2012 Arlin Davis <ardavis@ichips.intel.com> - 2.0.35
@@ -154,7 +219,7 @@ rm -rf %{buildroot}
 * Tue Feb 23 2010 Arlin Davis <ardavis@ichips.intel.com> - 2.0.27
 - DAT/DAPL Version 2.0.27 Release 1, OFED 1.5.1  
 
-* Tue Jan 11 2010 Arlin Davis <ardavis@ichips.intel.com> - 2.0.26
+* Mon Jan 11 2010 Arlin Davis <ardavis@ichips.intel.com> - 2.0.26
 - DAT/DAPL Version 2.0.26 Release 1, OFED 1.5, OFED 1.5-RDMAoE  
 
 * Tue Nov 24 2009 Arlin Davis <ardavis@ichips.intel.com> - 2.0.25
@@ -202,7 +267,7 @@ rm -rf %{buildroot}
 * Sun Jul 20 2008 Arlin Davis <ardavis@ichips.intel.com> - 2.0.11
 - DAT/DAPL Version 2.0.11 Release 1, IB UD extensions in SCM provider 
 
-* Tue Jun 23 2008 Arlin Davis <ardavis@ichips.intel.com> - 2.0.10
+* Mon Jun 23 2008 Arlin Davis <ardavis@ichips.intel.com> - 2.0.10
 - DAT/DAPL Version 2.0.10 Release 1, socket CM provider 
 
 * Tue May 20 2008 Arlin Davis <ardavis@ichips.intel.com> - 2.0.9
